---
title: "Influence of economic factors on cross-sectional equity factors"
output:
  pdf_document: default
  html_document: default
---

## Data  Preparation

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(lubridate)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
inflation <- read.csv("CPIAUCSL.csv")
predictor_df <- read.csv("PredictorLSretWide.csv")
predictor_df$date <- as.character(seq(as.Date("1926/01/01"), as.Date("2020/12/01"), by = "month"))
inflation <-inflation %>% rename(date=DATE)
data_inflation_1 <- inner_join(predictor_df,inflation)
data_inflation_1 <- data_inflation_1 %>% select(-date)

library(data.table)
inflation_2 <- data.frame( inflation= shift(inflation$CPIAUCSL_PC1,n=1,type="lag")[2:(length(inflation$CPIAUCSL_PC1)-1)],date=inflation$date[2:(length(inflation$date)-1)])
data_inflation_2 <- inner_join(predictor_df,inflation_2)
data_inflation_2 <- data_inflation_2 %>% select(-date)

library(data.table)
M2 <- read.csv("WM2NS.csv")
M2 <- data.frame( M2= shift(M2$WM2NS_PC1,n=1,type="lag")[2:(length(M2$WM2NS_PC1)-1)],date=M2$DATE[2:(length(M2$DATE)-1)])
M2$M2<-as.numeric(M2$M2)
data_m2 <- inner_join(predictor_df,M2)
data_m2<- data_m2 %>% select(-date)
interest_rate_spreads  <- read.csv("T10Y2Y.csv")
interest_rate_spreads <- data.frame( interest_rate_spreads= shift(interest_rate_spreads$T10Y2Y,n=1,type="lag")[2:(length(interest_rate_spreads$T10Y2Y)-1)],date=interest_rate_spreads$DATE[2:(length(interest_rate_spreads$DATE)-1)])
interest_rate_spreads$interest_rate_spreads<-as.numeric(interest_rate_spreads$interest_rate_spreads)
data_interest_rate <- inner_join(predictor_df,interest_rate_spreads)
data_interest_rate <- data_interest_rate %>% select(-date)
```

```{r message=FALSE, warning=FALSE,  paged.print=FALSE}
correlation_inflation_1_func <- function(a) {
  correlation <- cor(data_inflation_1[a],data_inflation_1$CPIAUCSL_PC1,use = "pairwise.complete.obs")
}
correlation_inflation_2_func <- function(a) {
  correlation <- cor(data_inflation_2[a],data_inflation_2$inflation,use = "pairwise.complete.obs")
}
correlation_m2_func <- function(a) {
  correlation <- cor(data_m2[a],data_m2$M2,use = "pairwise.complete.obs")
}
correlation_interest_rate_func <- function(a) {
  correlation <- cor(data_interest_rate[a],data_interest_rate$interest_rate_spreads,use = "pairwise.complete.obs")
}
```

## Analyses

### Inflation

```{r message=FALSE, warning=FALSE,  paged.print=FALSE}
correlation_inflation_1 <-data.frame(factor=names(data_inflation_1),correlation = sapply(c(1:length(data_inflation_1)), correlation_inflation_1_func)) 
correlation_inflation_1 %>% filter(abs(correlation)>0.1)%>% arrange(desc(abs(correlation))) 
```


```{r message=FALSE, warning=FALSE,  paged.print=FALSE}
correlation_inflation_2 <-data.frame(factor=names(data_inflation_2),correlation = sapply(c(1:length(data_inflation_2)), correlation_inflation_2_func)) 
correlation_inflation_2 %>% filter(abs(correlation)>0.1)%>% arrange(desc(abs(correlation))) 
```

```{r message=FALSE, warning=FALSE,  paged.print=FALSE}
data_inflation_2 %>% ggplot(aes(inflation,DivSeason))+geom_point()+geom_smooth(method = "lm")
```

### M2 

```{r message=FALSE, warning=FALSE,  paged.print=FALSE}

correlation_m2 <-data.frame(factor=names(data_m2),correlation = sapply(c(1:length(data_m2)), correlation_m2_func)) 
correlation_m2 %>% filter(abs(correlation)>0.1)%>% arrange(desc(abs(correlation))) 

```
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
data_m2 %>% ggplot(aes(M2,AdExp))+geom_point()+geom_smooth(method = "lm")
```

### interest_rate_spreads

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
correlation_interest_rate <-data.frame(factor=names(data_interest_rate),correlation = sapply(c(1:length(data_interest_rate)), correlation_interest_rate_func)) 
correlation_interest_rate %>% filter(abs(correlation)>0.1)%>% arrange(desc(abs(correlation))) 
```



```{r message=FALSE, warning=FALSE, paged.print=FALSE}
data_interest_rate %>% ggplot(aes(interest_rate_spreads,AnalystRevision))+geom_point()+geom_smooth(method = "lm")
```

# References 

### Data
```{r}
@article{ChenZimmermann2021,
  title={Open Source Cross Sectional Asset Pricing},
  author={Chen, Andrew Y. and Tom Zimmermann},
  journal={Critical Finance Review},
  year={Forthcoming}
}
```

